name: Build

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.6'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Prepare overage tools
        shell: bash
        run: |
          curl https://qlty.sh | sh
          ln -s ~/.qlty/bin/qlty ./qlty
      - name: Run the default task
        run: |
          bundle exec rake
          ./qlty coverage publish --token ${{ secrets.QLTY_TOKEN }} --report-format cobertura ./coverage/coverage.xml
