name: Build

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.6'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Prepare overage tools
        shell: bash
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Run the default task
        run: |
          # export CC_TEST_REPORTER_ID="${{ secrets.CC_TEST_REPORTER_ID }}"
          bundle exec rake
          # ./cc-test-reporter format-coverage --input-type cobertura ./coverage/coverage.xml
          # if [[ "$?" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
